set -g prefix C-b
set -g base-index 1
set -g escape-time 0
set -g history-limit 10000
set -g mode-keys vi
set -g mouse on
set -g default-shell /bin/bash

set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d m'
set -g focus-events on
set -g display-time 700

unbind C-f
bind C-b send-prefix

unbind '"'
unbind %
bind '-' split-window -v -c "#{pane_current_path}"
bind '\' split-window -h -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"
bind -n S-left prev
bind -n S-right next

bind -n 'M-1' select-window -t 1
bind -n 'M-2' select-window -t 2
bind -n 'M-3' select-window -t 3
bind -n 'M-4' select-window -t 4
bind -n 'M-5' select-window -t 5
bind -n 'M-6' select-window -t 6
bind -n 'M-7' select-window -t 7
bind -n 'M-8' select-window -t 8
bind -n 'M-9' select-window -t 9

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

set -g set-titles on
set -g set-titles-string "#T"
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

setw -g mode-style "fg=color0 bg=color2"
set -g pane-border-style "fg=color8"
set -g pane-active-border-style "fg=color2"

set -g status-style "bg=default,fg=color7"
set -g status-position bottom
set -g status-justify absolute-centre

set -g status-left "#[fg=color2,bold][#S]"
set -g status-right "#[fg=color2,bold]#{?client_prefix,<P> ,}#[fg=color7]%H:%M#[fg=color8] | #[fg=color7]%d/%b/%Y"
set -g status-right-length 100
set -g status-left-length 100

set -g window-status-format "#[fg=color8] #I:#W "
set -g window-status-current-format "#[fg=color2,bold,underscore] #I:#W "

set -g message-style "bg=color2 fg=color0"
