# Same color inside tmux and base terminal
set -g default-terminal "xterm-256color"
set -g terminal-overrides ",xterm-256color:Tc"
set -g focus-events on

# Base tmux
set -s escape-time 0
set -g base-index 1
set -g display-time 700
set -g history-limit 10000
set -g mouse on

# Bindings
unbind C-b
set -g prefix C-t
bind C-f send-prefix
bind C-a send-prefix

# Window split
unbind '"'
unbind %
bind '-' split-window -v
bind '\' split-window -h

# Window switching
bind -n S-down new-window
bind -n S-left prev
bind -n S-right next

bind -n 'M-1' select-window -t 1
bind -n 'M-2' select-window -t 2
bind -n 'M-3' select-window -t 3
bind -n 'M-4' select-window -t 4
bind -n 'M-5' select-window -t 5
bind -n 'M-6' select-window -t 6
bind -n 'M-7' select-window -t 7
bind -n 'M-8' select-window -t 8
bind -n 'M-9' select-window -t 9

# Vim-like pane switching
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Resizing pane
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# (r)eload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Allow the title bar to adapt to whatever host you connect to
set -g set-titles on
set -g set-titles-string "#T"

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none



# Colorscheme
WHITE="#FFFFFF"
BLACK="#000000"
CURRENT_BG="#5F8787"
CURRENT_FG="#000000"
LIGHT_FG="#395151"

# copy mode
setw -g mode-style "fg=#DDDDDD bg=#084f67"

# pane borders
set -g pane-border-style 'fg=#5F8787'
set -g pane-active-border-style 'fg=#666666'

# statusbar
wg_sep="#[fg=${WHITE}] = "
wg_prfx="#[fg=${LIGHT_FG}]#{?client_prefix,[Prefix],} "
wg_time="#[fg=${CURRENT_FG}]%H#[fg=${LIGHT_FG}]:#[fg=${CURRENT_FG}]%M"
wg_date="#[fg=${CURRENT_FG}]%d#[fg=${LIGHT_FG}]/#[fg=${CURRENT_FG}]%b#[fg=${LIGHT_FG}]/#[fg=${CURRENT_FG}]%Y"

set -g status-style bg=${CURRENT_BG},fg=${CURRENT_FG}
set -g status-left "#[fg=${CURRENT_FG}][#[fg=${CURRENT_FG}]#S#[fg=${CURRENT_FG}]]"
set -g status-right ${wg_prfx}${wg_time}${wg_sep}${wg_date}
set -g status-justify absolute-centre
set -g status-position bottom
set -g status-right-length 100
set -g status-left-length 100

set -g window-status-format "#[bg=${CURRENT_BG},fg=${LIGHT_FG}]#I#[bg=${CURRENT_BG},fg=${LIGHT_FG}]:#[bg=${CURRENT_BG},fg=${LIGHT_FG}]#W"
set -g window-status-current-format "#[bg=${CURRENT_BG},fg=${CURRENT_FG}]#I#[bg=${CURRENT_BG},fg=${CURRENT_FG}]:#[bg=${CURRENT_BG},fg=${CURRENT_FG}]#W"

# messages
set -g message-style "bg=#a06666 fg=${BLACK}"

